#!/usr/bin/env bash
set -euo pipefail

trap 'exit 0' INT TERM

export GUM_CHOOSE_CURSOR_FOREGROUND=6
export GUM_CHOOSE_SELECTED_FOREGROUND=6

clear

title="Power Menu:"
indent=10

header=""
for (( i=0; i<indent; i++)); do
    header+=" "
done
header+="$title"

if ! choice=$(gum choose \
    --header="$header" \
    --cursor="> " \
    --height=2 \
    --padding="0 0" \
    "Shutdown" \
    "Reboot"); then
    exit 0
fi

confirm() {
    gum confirm "$1" --default=false
}

case "$choice" in
    "Shutdown")
        hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'
        ;;
    "Reboot")
        hyprshutdown -t 'Restarting...' --post-cmd 'reboot'
        ;;
esac
