bind C-b
set -g prefix F10 # F10 was changed to CAPS-LOCK in os.

set -sg escape-time 0

bind l resize-pane -L 5
bind r resize-pane -R 5
bind | split-window -h
bind - split-window -v
bind  Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R
bind a new-window
bind-key N command-prompt -p "New session name:" "new-session -s '%%'"
bind x kill-pane

set -g history-limit 100000
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind s choose-tree -ZsK '#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}'

bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"


set -g status-right '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{s|^/home/random|~|:pane_current_path}" %H:%M %d-%b-%y'
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"



# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
